T0nj3/auction-room

css/output.css
index.html
js/carousel.js
tailwind.config.js

Added content and styling for landing page, not finished

first commit for landing page/index

---

package-lock.json
package.json

Added live server to the app. 
just use command npm run start

added liveserver in package json

---

auth/login.html
css/output.css
tailwind.config.js

Fixed the font family. 
fixed the font on the login page

fikset opp i font family byttet om inter og playfer fontene

---

auth/login.html
js/auth_js/apiauth.js
js/auth_js/handel/login.js

added fetch call and import it to login.js
Added login function to the app
Have not made a error message yet

added fetch call and import it to login.js

---

css/output.css
index.html
js/apiutils.js
js/carousel.js
js/detail-listing.js
js/listings.js
listings/detail-listing.html

Build listing detail page: fetch data from API, render auction info, seller, bids, and leader using DOM methods, fetched data from API to index for the carousels

Build listing detail page+index with API intergration

---

auth/register.html
js/auth_js/apiauth.js
js/auth_js/handel/registration.js

Made the Api function to reg.
made a function so we ca reg a new user
belong to issue #26 and #23

Made function and API for reg

---

auth/login.html
auth/register.html
js/auth_js/error/errorAuth.js
js/auth_js/handel/login.js
js/auth_js/handel/registration.js

Created a new JS file that handles login and registration errors.
Imported validation into registration.js and login.js from errorAuth.js.
Updated login.html and registration.html so that we have divs to display errors.

Created error handlings to reg and log in

---

profile/index.html

Have added header and footer 
Have set up meta description, tags author 
fixed the links  in the header
set up the scelleton to hmtl

setup html to profile site.

---

auth/register.html
js/auth_js/error/errorAuth.js

I have set up the JS folder and the files for the profile page.
I have linked the JS file that should connect to profile.html.
I have also fixed some of the error code related to login and register.

Made a js maps

---

js/profile-js/apiprofile.js
js/profile-js/services/fetchapi.js
profile/index.html

"I've set up the fetch for the profile page.
But I can't get the individual page to show up. I get all the profiles or no profiles at all.
I created a function that redirects the user back to index.html if they are not logged in."

Satt opp fetch til profilsiden

---

auth/login.html
auth/register.html
index.html
listings/detail-listing.html
listings/feed.html
profile/index.html

added links to the header so  we can walk from one page to another.

link the pages

---

js/profile-js/services/fetchapi.js
profile/index.html

- have got the banner to show on html
- have got avatar to show on html
- got name to show on html
- got bio to show on html
hav not fully style it yet

Have got the data from api to html

---

css/output.css
js/profile-js/services/fetchapi.js
profile/index.html

Added banner
added avatar
added name 
added bio
made all responsive

fixed, header and banner an made it responsive.

---

css/output.css
js/profile-js/apiprofile.js
profile/index.html

got the api so the user can change there bio avatar and banner. 
have made a form where the usser can put in there inputts. 
it does not work yet have not made a i funktion to send the changes to the api. 
have only got the api.

made form that let et user change there profile

---

js/profile-js/services/fetchapi.js
profile/index.html

There are som bugs that need to bi fixed. 
the user hva to reload the page to update profile settings like bio, avatar etc. 
we need to hide the seciton.

Fixed the  form to update page

---

js/profile-js/apiprofile.js
js/profile-js/services/fetchapi.js
profile/index.html

User can now make auction post. 
if a user are loged in then then a user can make a post. 
made a form that need to be field out with title, image, description and due date
page realode when you submit it

user can make a post

---

css/output.css
js/profile-js/apiprofile.js
js/profile-js/services/fetchapi.js
js/profile-js/services/listings_profile.js
profile/index.html

I created a new file to make it more organized. This file will only contain the listings and listing wins, which helps keep the code smaller and more manageable in the profile.
Now, users can see their listings on their profile page.
This is not styled yet.

so the user can see there own listing

---

css/output.css
js/profile-js/apiprofile.js
js/profile-js/services/fetchapi.js
js/profile-js/services/listings_profile.js
profile/index.html

Added  delte button and edit. 
Link api delete and put to the prosject. 
Made a delete button that send a delete request to the api
made a edit button that allow the user to change there posts. 
made a form that need to be filed in html
the form shows when user pres edit button
need to be styled

added delete button and edit button

---

css/output.css
js/profile-js/apiprofile.js

fixed the url to edit fetch. 
change it when i worked on edit listings
fixed now

fixed edit profile

---

css/output.css
js/profile-js/fuction/button.js
js/profile-js/services/fetchapi.js
js/profile-js/services/listings_profile.js
profile/index.html

Completed styling for profile page.
- Hidden "User Posts" and "Winning Posts" sections by default.
- Users now need to click the respective buttons to reveal active posts.
- Made "User Post" cards responsive: they shrink when the screen size reduces,
ensuring better display on smaller screens.
Create post and fonts
- Updated fonts on product cards and the 
- made a "Create a Post" button for a more consistent look.

profile page is done

---

css/output.css
js/profile-js/services/public-profile.js
profile/public-profile.html

style: update user profile layout to match public profile design
- matched layout structure with public profile
- added absolute positioned avatar over banner
- unified spacing, text sizes, and colors with public version
- made profile responsive with consistent paddings and font scaling
- aligned banner height and avatar size across breakpoints

Styled User profile

---

css/output.css
index.html

Fixed the picture of the car at index. 
The gap between the text and the image is fixed

fixed the picture of the car

---

css/output.css
js/profile-js/services/listings_profile.js
profile/index.html

Fixed the button that on the listing, 
delete button is now hovering lik edit button. 
we have moved create button up

Fixed the button on profile site

---

js/profile-js/services/listings_profile.js

delete the hover effect on product card.

deleted hover effect profile site

---

js/profile-js/apiprofile.js

Allow the user to only fill in one input at edit profile form. 
belong to issu #115

just fill one input on edit profile

---

js/profile-js/services/fetchapi.js
js/profile-js/services/listings_profile.js

Relocated the displayWinningAuctions function from fetchapi.js to listing_profile.js for better separation of concerns and file structure.
No functional changes, only code organization improvements.

Moved won auction function from fetchAPI to ListingProfile.js

---

auth/login.html
auth/register.html
css/output.css
js/auth_js/apiauth.js
js/auth_js/error/errorAuth.js
js/auth_js/handel/login.js
js/auth_js/handel/registration.js

loading indicator + error handling/message done for login and register

loading indicator + error handling/message done for login and register

---

css/output.css
js/profile-js/services/listings_profile.js

Made the imgae clickable with the url to the product detail pagel.

Make listing image clickable with URL constant profile page

---

auth/login.html
auth/register.html
css/output.css
js/auth_js/error/errorAuth.js
js/profile-js/services/public-profile.js
profile/public-profile.html

Made det error color white so it easyer for the user to reed. 
fixed the button on user profile so the active button is brown.

fixed auth error color. fixed active button

---

css/output.css
js/profile-js/services/fetchapi.js
profile/index.html

Improved the styling of the "updated successfully" success message to match the figma design system.

Fixed the style sucsess

---

js/profile-js/apiprofile.js
js/profile-js/services/fetchapi.js
js/profile-js/services/listings_profile.js
profile/index.html

made a function to see the bid history in html document.
some issue. cant see title, picture or ending on html.
cant find the data in the api

added a fetch to see bid history.

---

js/profile-js/apiprofile.js
js/profile-js/fuction/button.js
profile/index.html

made a function that let the user see there bid history.
made a button that set the section active.

you can now see the data in bid history

---

css/output.css
js/profile-js/fuction/button.js
js/profile-js/services/fetchapi.js
js/profile-js/services/listings_profile.js

This PR fixes the issue where user posts did not load correctly on the first page visit and required multiple refreshes. It also ensures proper reloading of the UI after closing the edit product form. 
fixes: 
Auctions now load immediately on first profile page load.
Layout no longer breaks after closing the edit product form.
Display now consistent across desktop and mobile.

Fixed the bug on profile site

---

css/output.css
js/profile-js/services/listings_profile.js
profile/index.html

Fixed the product card on profile site so there apper smaller 
made the section for the card tigther so there are more room on the left and right side

fixed the section for product card profile site

---

css/output.css
listings/detail-listing.html

place the seller text correct. 
place the section more to the middel

fixed listing page

---

css/output.css
index.html
js/listings.js

fixed so the user can see the time left on product card.

fixed time

---

auth/register.html
css/output.css
index.html
js/apiutils.js
listings/detail-listing.html
listings/feed.html
profile/public-profile.html

Fixed so the user can see the current price on the product. 
added meta text
meta description 
meta tags
authors
meta text is fixed on index, listing, details and public profile

Fixed card and meta text

---

css/output.css
index.html

Fixed the font to header on wlecome section on index

fixed font on welcome section

---

auth/login.html
auth/register.html
index.html
listings/detail-listing.html
listings/feed.html
profile/index.html
profile/public-profile.html

add anchor tag on the log the let the user go back to home page

add anchor tag

---

css/output.css
profile/index.html

Change the button name to your acution insted. So it is easier for the user to unserstand that is all you acutions and not active

Fixed the active acution button

---

js/detail-listing.js
js/hamburger.js

removed som comments and console.log

fixed hamburger and detail-listing"
